language: python
python:
  - "2.7"
  - "3.5"

script: bash functional-tests.sh

install:
    - sudo apt-get update
    - unset PYTHONPATH
    - unset PYTHONHOME
    - unset PYTHONUSER
    - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
        wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
      else
        wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
      fi
    - bash miniconda.sh -b -p $HOME/miniconda
    - export PATH="$HOME/miniconda/bin:$PATH"
    - hash -r
    - conda config --set always_yes yes --set changeps1 no
    - conda install conda-build
    - conda update -q conda conda-build
    - conda install -y conda-build-all -c conda-forge
    - conda install -y anaconda-client
    - conda config --add channels bioconda
    - pip install -r requirements.txt
    - conda install -y "gsort>=0.0.2" samtools htslib zlib check-sort-order
    - python setup.py install
